name: Compile SCSS

on:
  push:
    branches: [ "master" ]
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm ci --no-audit --progress=false || true
          npm install -g sass@1.78.0

      - name: Compile SCSS
        run: |
          sass assets/sass/split.scss:assets/css/split.css --no-source-map --style=expanded

      - name: Commit compiled CSS
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/css/split.css || true
          if ! git diff --staged --quiet; then
            git commit -m "ci: compile SCSS -> CSS [skip ci]" || true
            git push
          else
            echo "No changes to compiled CSS"
          fi
